version: 0.2

phases:
  install:
    run-as: root
    on-failure: ABORT
    # runtime-versions:
    #   runtime: version
    #   runtime: version
    commands:
      - echo "--------------------------------Installing yq library--------------------------------"
      - sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      - sudo chmod +x /usr/bin/yq
  pre_build:
    commands:
      - echo "--------------------------------Logging in to Amazon ECR--------------------------------"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "--------------------------------Build started on `date`--------------------------------"
      - echo "--------------------------------Building the Docker image--------------------------------"        
      - docker build -t $IMAGE_REPO_NAME:node-alpine3.18 .
      - docker tag $IMAGE_REPO_NAME:node-alpine3.18 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ENVIRONMENT/$IMAGE_REPO_NAME:node-alpine3.18      
  post_build:
    commands:
      - echo "--------------------------------Build completed on `date`--------------------------------"
      - echo "--------------------------------Pushing the Docker image--------------------------------"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ENVIRONMENT/$IMAGE_REPO_NAME:node-alpine3.18
      - echo "--------------------------------Updating fsa-stack helm chart repository with latest image tag--------------------------------"
      - git clone https://github.com/giraffeman123/fsa-stack.git
      - cd fsa-stack/
      - yq -i '.deployment.fsaApi.imageTag="node-alpine3.18"' values.yaml
      - git add .
      - git commit -m "updated fsa-api image tag to node-alpine3.18"
      - git push origin main